### ISSUE TITLE
selecting new name for imgpkg

### ISSUE THREAD

**Issue by jessehu** [k14s/imgpkg#2]
`imgpkg (pronounced: image package) allows to store sets of files (e.g. application configuration) as images in Docker (OCI) registries. `

If 'image package' means package an docker image, the name is good; if it means k8s application configuration package, then a name like 'configpkg' or 'konfigpkg' is better :D

**Comment by cppforlife** [comment]
yeah i can see that. i wanted to somehow convey it's based on registry. smaller use case i guess is that you can use this tool to pkgs non-configuration as well (eg binaries).

**Comment by jessehu** [comment]
Make sense! We ever worked on packaging data files generated from Machine Learning training service into docker images and sharing accoss ML serving service running in containers.

**Comment by btwiuse** [comment]
I'd like to suggest an alternative name: `dkg`, short for `docker package`, or simply `dockage`

**Comment by gcheadle-vmware** [comment]
The team has decided to keep the imgpkg name. We have already introduced imgpkg in our community meetings and presentations, a new name would also have to follow open source guidelines from VMware.

**Comment by jessehu** [comment]
Thank you!
