### ISSUE TITLE
Request for new release 

### ISSUE THREAD

**Issue by jessehu** [k14s/imgpkg#3]
The latest release v0.1.0 was published on Nov 2, 2019. There are several commits after then. Should we create a new release like 0.1.1 or 0.2.0? Thanks.

**Comment by cppforlife** [comment]
will cut 0.2.0.

**Comment by jessehu** [comment]
Thanks!

**Comment by cppforlife** [comment]
apologies for delay. this fell off my table. https://github.com/k14s/imgpkg/releases/tag/v0.2.0
